Iter18
Schalure/urlalias pull request #21
Opened 2024-02-28 12:14 UTC by Schalure

2024-02-29 17:30 UTC, s-shpak requested changes
В папке profiles должен лежать оригинальный и оптимизированный профили. Сейчас, насколько я понимаю, там лежат профили, полученные при запуске бенчмарок. Тестируемые функции не удалось оптимизировать ?

2024-03-05 20:42 UTC, Schalure commented
> В папке profiles должен лежать оригинальный и оптимизированный профили. Сейчас, насколько я понимаю, там лежат профили, полученные при запуске бенчмарок. Тестируемые функции не удалось оптимизировать ?

Я переделал обработчик GetBatchShortURL. Там теперь только 2 запроса к БД. Раньше были запросы на каждую ссылку для преобразования. Теперь я пытаюсь получить все ключи по оригинальным ссылкам. Дальше сравниваю какие получил, недостающие генерирую и сохраняю. Остальные просто отправляю обратно.

2024-03-06 10:31 UTC, s-shpak requested changes

2024-03-06 10:31 UTC, s-shpak commented on internal/app/storage/postgrestor/postgrestor.go
> +	rows, err := s.db.Query(ctx, `SELECT original_url, short_key FROM aliases where original_url IN (`+strings.Join(params, ", ")+`);`)
Это чревато SQL-инъекцией. Здесь пример, как это можно решить: https://stackoverflow.com/a/48070387

2024-03-06 10:31 UTC, s-shpak commented on internal/app/aliasmaker/aliasmaker.go
> +	// for i, originalURL := range batchOriginalURL {
Не оставляй такой deadcode

2024-03-06 12:25 UTC, Schalure commented on internal/app/storage/postgrestor/postgrestor.go
> +	rows, err := s.db.Query(ctx, `SELECT original_url, short_key FROM aliases where original_url IN (`+strings.Join(params, ", ")+`);`)
Спасибо. Знал, что так не очень хорошо. Но не нашел нормального примера. Спасибо. Переделал.

2024-03-06 16:42 UTC, s-shpak approved these changes

2024-03-07 07:21 UTC, merged