Iter20
Schalure/urlalias pull request #23
Opened 2024-03-10 15:23 UTC by Schalure

2024-03-10 15:27 UTC, Schalure commented
Я правильно понял? В последнем инкременте нужно добавить только 3 переменные?

2024-03-10 20:15 UTC, s-shpak requested changes

2024-03-10 20:15 UTC, s-shpak commented on cmd/staticlint/main.go
> +			if c, ok := node.(*ast.CallExpr); ok {
По ТЗ тебе необходимо проверить, что вызов `os.Exit` совершается из функции `main`, а не из любой функции пакета `main`

2024-03-10 20:15 UTC, s-shpak commented on cmd/staticlint/main.go
> +						fmt.Printf("%v: Direct call to os.Exit from the main package\n", pass.Fset.Position(pack.Pos()).String())
Тебе надо зарепортить эту ошибку через этот метод `pass`: https://smartbft-go.github.io/godoc/pkg/golang.org/x/tools/go/analysis/index.html#Pass.Reportf

2024-03-10 20:15 UTC, s-shpak commented on cmd/shortener/main.go
> +	buildVersion string = "N/A"
Добавь, пожалуйста, в ридми инструкции по тому, как инджектить эти переменные

2024-03-11 07:00 UTC, Schalure commented on cmd/staticlint/main.go
> +			if c, ok := node.(*ast.CallExpr); ok {
Сори, не правильно прочитал

2024-03-11 10:00 UTC, Schalure commented on cmd/shortener/main.go
> +	buildVersion string = "N/A"
В ридми на гитхабе или в godoc?

2024-03-11 19:43 UTC, s-shpak approved these changes

2024-03-12 11:07 UTC, merged