Iter5
Schalure/urlalias pull request #6
Opened 2023-10-11 11:53 UTC by Schalure

2023-10-12 07:02 UTC, capsulated requested changes
❌ - критичные комментарии, которые обязательны к исправлению  
⚠️ - важные комментарии, которые очень желательно изучить и исправить

2023-10-12 10:56 UTC, Schalure commented on cmd/client/main.go
> +func main() {
В 7-ом уроке первой темы было сказано: 
> Если вы выбрали трек «Сервис сокращения URL», вы можете сохранить код в файле main.go поддиректории cmd/client вашего проекта. Тогда у вас всегда будет под рукой программа для проверки сервиса.

Я его не дорабатывал. Просто сохранил, думал возможно потом понадобится и сделаю рабочим

2023-10-12 10:57 UTC, Schalure commented on cmd/shortener/config/config.go
> +		} else {
Я не понимаю как можно облегчить эту конструкцию.

2023-10-12 11:07 UTC, Schalure commented on cmd/shortener/config/configmodel.go
> +		log.Fatal("Repeated method call")
Задумка была в том, чтобы реализовать Singleton. Ведь инициализация конфига должна быть только один раз за приложение. Подскажи тогда пожалуйста, если не fatal, то что тут лучше использовать? Ошибку вернуть?

2023-10-12 11:09 UTC, Schalure commented on cmd/shortener/config/configmodel.go
> +func (c *Configuration) Host() string {
Я предполагал, что эти поля должны быть только для чтения. Не стоит?

2023-10-12 11:10 UTC, Schalure commented on models/model.go
> +package models
В задании было сказано, что стоит погуглить паттерн repository. Я погуглил, нашел проектик и там была такая структура.

2023-10-12 11:13 UTC, Schalure commented on internal/app/storage/storage.go
> +func GetAliasKey(longURL string) (string, bool) {
storage который в internal остался от 1-го инкремента. Забыл удалить.

2023-10-16 12:06 UTC, capsulated commented on cmd/client/main.go
> +func main() {
Лучше удалить его, либо в .gitignore поставить, чтобы не мешался

2023-10-16 17:28 UTC, Schalure commented on cmd/shortener/config/config.go
> +	return nil
Я правда не понимаю какой return убрать. Тот, что в самом низу. Если убрать, компилятор выдаст ошибку, что функция не возвращает значение:
`func checkBaseURL(baseURLFromOpt string) error {

	var strs = strings.SplitAfterN(baseURLFromOpt, "//", 2)
	if len(strs) != 2 {
		return fmt.Errorf("ip addres in not right format: %s. for example: http://192.168.1.2:port", baseURLFromOpt)
	}

	if strs[0] != "http://" && strs[0] != "https://" {
		return fmt.Errorf("base url in not right format: %s. for example: http://192.168.1.2:port", baseURLFromOpt)
	}

	args := strings.Split(strs[1], ":")
	if len(args) != 2 {
		return fmt.Errorf("ip addres and port in not right format: %s. for example: 192.168.1.2:port", strs[1])
	}

	if args[0] != "localhost" && net.ParseIP(args[0]) == nil {
		return fmt.Errorf("ip addres in not right format: %s. for example: http://192.168.1.2:port", baseURLFromOpt)
	}

	if _, err := strconv.Atoi(args[1]); err != nil {
		return fmt.Errorf("ort in not right format: %s. for example: http://addres:80", baseURLFromOpt)
	}

//	return nil
}` 

С var config *Configuration = nil все понял. Это наверное по привычке, что все переменные должны быть явно инициализированы. Сделаю

2023-10-16 17:43 UTC, Schalure commented on cmd/shortener/config/config.go
> +		} else {
Если так сделать, то можно затереть значение, которое получено через флаги приложения
Функции запускаются в таком порядке:

```
config.parseFlags()
config.parseEnv()
```

2023-10-19 17:38 UTC, merged